package com.example.eyecare20_20_20.utils

object Constants {
    const val INITIAL_DURATION_MINUTES = 20L
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_PAUSE = "ACTION_SERVICE_PAUSE"
    const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"

    const val TIMER_STATE = "TIMER_STATE"

    const val NOTIFICATION_CHANNEL_ID = "EYECARE_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "EYECARE_NOTIFICATION"
    const val NOTIFICATION_ID = 10

    const val CLICK_REQUEST_CODE = 100
    const val CANCEL_REQUEST_CODE = 101
    const val STOP_REQUEST_CODE = 102
    const val RESUME_REQUEST_CODE = 103
}